# Generated by Django 4.1.7 on 2023-04-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_coupon_order_store_alter_item_quantity_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
