# Generated by Django 2.2.13 on 2023-04-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_delete_coupon_remove_order_items_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
